### ISSUE TITLE
Adding Records and Resolvers Exhibits Inconsistent Behavior

### ISSUE THREAD

**Issue by chris-remus** [ensdomains/ens-app#71] opened 2019-01-04 17:19 UTC
Regarding records and resolver setting - 

<img width="1321" alt="screen shot 2019-01-04 at 12 16 12 pm" src="https://user-images.githubusercontent.com/6430200/50701113-97979a80-101a-11e9-825f-0dd9fe547b64.png">

Adding records and resolver transactions are initiated in the Dapp and confirmed in Metamask. The Dapp exhibits these behaviors, across Chrome and Firefox to varying degrees -

1 - After Tx confirmation, resolver doesn't appear set unless page is refreshed, sometimes it doesn't appear at all.

2 - After Tx confirmation, records don't appear set, even after page refresh.

**Comment by makoto** [comment] 2019-01-05 02:43
Looks like this happens when tried with public network (tried with Ropsten) but not on local in memory version (aka ganache).

I noticed that following error message when we see the problem happening. Maybe something to do with timing (local version transition quicker than public node version).

```index.js:1452 Warning: Cannot update during an existing state transition (such as within `render`). Render methods should be a pure function of props and state.
```

I will look into more detail.

**Comment by makoto** [comment] 2019-01-08 02:09
@chris-remus fixed the bug and deployed again. There is still a few sec time lag but should rerender on its own.

**Comment by jefflau** [comment] 2019-01-24 06:03
Closing this. Reopen if still an issue

**Comment by Arachnid** [comment] 2019-04-09 09:22
I just noticed this with setting a resolver on Goerli.

**Comment by jefflau** [comment] 2019-04-09 09:24
@Arachnid What exact behaviour did you see nick? Can you give instructions for replication?

@makoto Can you take a look at this?

**Comment by Arachnid** [comment] 2019-04-09 09:27
I set a resolver for the first time. It shows the 'tx pending' spinner, then after a while that goes away and the page reloads, but still shows 0x0... as the resolver address. A few seconds later, Metamask reports the transaction as mined, and I have to manually reload the page to see the new resolver.

**Comment by jefflau** [comment] 2019-04-09 09:29
That sounds a little bit different than the bug Chris reported. Can you reproduce the bug on Ropsten? I was having a lot of issues with Goerli not giving me the `txReceipt` event from web3, which is why I asked you to deploy on ropsten

**Comment by Arachnid** [comment] 2019-04-10 10:11
>  1 - After Tx confirmation, resolver doesn't appear set unless page is refreshed, sometimes it doesn't appear at all.

I think this is the same bug as Chris reported.

I can't seem to reproduce it on Ropsten. Goerli is definitely reloading, though - it just seems to happy too early.

**Comment by Arachnid** [comment] 2019-04-10 23:59
In a conversation with @michaelelliot we just realised the probable cause of this: The calls to update the UI after the transaction is mined are going to a node that's a block behind, and so aren't reflecting the new state.

**Comment by jefflau** [comment] 2019-04-11 05:07
That makes sense. Especially since Goerli confirms so quickly. Is there something we can do?

**Comment by michaelelliot** [comment] 2019-04-11 09:58
[Multicall.js](https://github.com/makerdao/multicall.js) may be able to solve this for you (in a general purpose way), because it returns the block number along with the aggregated results from multiple calls.

**Closed** 2020-05-21 21:55 UTC
Labels: bug
